{
  aicPackage,
  pkgs,
}:
pkgs.runCommand "aic-test" {
  nativeBuildInputs = [
    pkgs.coreutils
    pkgs.git
    pkgs.gnugrep
    pkgs.jq
  ];
} ''
  set -euo pipefail

  test_root="$TMPDIR/aic-test"
  fake_bin="$test_root/bin"
  mkdir -p "$fake_bin" "$test_root/home"

  cat > "$fake_bin/codex" <<'SH'
  #!/bin/sh
  set -eu

  : "''${AIC_TEST_AGENT_ARGS:?}"
  printf '%s\n' "$@" > "$AIC_TEST_AGENT_ARGS"

  output_file=""
  while [ "$#" -gt 0 ]; do
    if [ "$1" = "--output-last-message" ]; then
      output_file="$2"
      shift 2
    else
      shift
    fi
  done

  if [ -n "''${AIC_TEST_AGENT_STDERR:-}" ]; then
    printf '%s\n' "$AIC_TEST_AGENT_STDERR" >&2
  fi
  exit_code="''${AIC_TEST_AGENT_EXIT:-0}"
  if [ "$exit_code" -ne 0 ]; then
    exit "$exit_code"
  fi
  if [ "''${AIC_TEST_AGENT_EMPTY:-0}" -ne 1 ]; then
    printf '%s\n\n%s\n' "Test commit" "- Generated by test fixture." > "$output_file"
  fi
  SH

  cat > "$fake_bin/opencode" <<'SH'
  #!/bin/sh
  set -eu

  case "''${1:-}" in
    run)
      : "''${AIC_TEST_AGENT_ARGS:?}"
      : "''${AIC_TEST_AGENT_CONFIG:?}"
      : "''${AIC_TEST_AGENT_INPUT:?}"
      : "''${OPENCODE_CONFIG_CONTENT:?}"
      printf '%s\n' "$@" > "$AIC_TEST_AGENT_ARGS"
      printf '%s\n' "$OPENCODE_CONFIG_CONTENT" > "$AIC_TEST_AGENT_CONFIG"
      cat > "$AIC_TEST_AGENT_INPUT"
      printf '%s\n' \
        '{"type":"step_start","sessionID":"ses_aic_test","part":{"type":"step-start"}}'

      if [ -n "''${AIC_TEST_AGENT_STDERR:-}" ]; then
        printf '%s\n' "$AIC_TEST_AGENT_STDERR" >&2
      fi
      exit_code="''${AIC_TEST_AGENT_EXIT:-0}"
      if [ "$exit_code" -ne 0 ]; then
        exit "$exit_code"
      fi
      if [ "''${AIC_TEST_AGENT_EMPTY:-0}" -ne 1 ]; then
        printf '%s\n' \
          '{"type":"text","sessionID":"ses_aic_test","part":{"type":"text","text":"Test commit\n\n- Generated by test fixture."}}'
      fi
      ;;
    session)
      : "''${AIC_TEST_DELETED_SESSION:?}"
      : "''${AIC_TEST_SESSION_ARGS:?}"
      printf '%s\n' "$@" > "$AIC_TEST_SESSION_ARGS"
      session_id=""
      for arg in "$@"; do
        session_id="$arg"
      done
      printf '%s\n' "$session_id" > "$AIC_TEST_DELETED_SESSION"
      delete_exit="''${AIC_TEST_SESSION_DELETE_EXIT:-0}"
      if [ "$delete_exit" -ne 0 ]; then
        printf '%s\n' "session delete failed" >&2
        exit "$delete_exit"
      fi
      ;;
    *)
      printf 'unexpected opencode command: %s\n' "''${1:-}" >&2
      exit 1
      ;;
  esac
  SH

  cat > "$fake_bin/editor" <<'SH'
  #!/bin/sh
  set -eu

  : "''${AIC_TEST_EDITED_MESSAGE:?}"
  cp "$1" "$AIC_TEST_EDITED_MESSAGE"
  SH

  chmod +x "$fake_bin/codex" "$fake_bin/opencode" "$fake_bin/editor"

  export HOME="$test_root/home"
  export PATH="$fake_bin:$PATH"
  export GIT_EDITOR="$fake_bin/editor"

  new_repo() {
    local name="$1"
    local repo="$test_root/$name"
    mkdir -p "$repo"
    git -C "$repo" init -q
    git -C "$repo" config user.name "AIC Test"
    git -C "$repo" config user.email "aic@example.invalid"
    printf '%s\n' "$name" > "$repo/change.txt"
    printf '%s\n' "$repo"
  }

  prepare_scenario() {
    local name="$1"
    export TMPDIR="$test_root/tmp-$name"
    export AIC_TEST_AGENT_ARGS="$test_root/$name.args"
    export AIC_TEST_AGENT_CONFIG="$test_root/$name.config"
    export AIC_TEST_AGENT_INPUT="$test_root/$name.input"
    export AIC_TEST_DELETED_SESSION="$test_root/$name.deleted-session"
    export AIC_TEST_EDITED_MESSAGE="$test_root/$name.message"
    export AIC_TEST_SESSION_ARGS="$test_root/$name.session-args"
    mkdir -p "$TMPDIR"
    unset AIC_AGENT AIC_MODEL
    unset AIC_TEST_AGENT_EMPTY AIC_TEST_AGENT_EXIT AIC_TEST_AGENT_STDERR
    unset AIC_TEST_SESSION_DELETE_EXIT
  }

  run_aic() {
    local repo="$1"
    shift
    (
      cd "$repo"
      ${aicPackage}/bin/aic "$@"
    )
  }

  assert_tmp_empty() {
    if find "$TMPDIR" -type f -print -quit | grep -q .; then
      echo "aic leaked a temporary file in $TMPDIR" >&2
      find "$TMPDIR" -type f -print >&2
      exit 1
    fi
  }

  assert_opencode_session_deleted() {
    test "$(cat "$AIC_TEST_DELETED_SESSION")" = "ses_aic_test"
    grep -Fx -- "session" "$AIC_TEST_SESSION_ARGS"
    grep -Fx -- "delete" "$AIC_TEST_SESSION_ARGS"
    grep -Fx -- "--pure" "$AIC_TEST_SESSION_ARGS"
    grep -Fx -- "ses_aic_test" "$AIC_TEST_SESSION_ARGS"
  }

  prepare_scenario help
  ${aicPackage}/bin/aic --help > "$test_root/help.out"
  grep -F -- '--agent NAME' "$test_root/help.out" || {
    echo "aic help does not document agent selection" >&2
    exit 1
  }
  grep -F -- 'AIC_AGENT' "$test_root/help.out"
  grep -F -- 'opencode/nemotron-3-ultra-free' "$test_root/help.out"

  prepare_scenario codex-default
  codex_default_repo="$(new_repo codex-default)"
  run_aic "$codex_default_repo"
  grep -Fx -- 'exec' "$AIC_TEST_AGENT_ARGS"
  grep -Fx -- '--ephemeral' "$AIC_TEST_AGENT_ARGS"
  grep -Fx -- '--sandbox' "$AIC_TEST_AGENT_ARGS"
  grep -Fx -- 'read-only' "$AIC_TEST_AGENT_ARGS"
  grep -Fx -- '--output-last-message' "$AIC_TEST_AGENT_ARGS"
  if grep -Fx -- '-m' "$AIC_TEST_AGENT_ARGS"; then
    echo "default Codex invocation unexpectedly selected a model" >&2
    exit 1
  fi
  test "$(git -C "$codex_default_repo" log -1 --pretty=%s)" = "Test commit"
  grep -F -- 'Test commit' "$AIC_TEST_EDITED_MESSAGE"
  assert_tmp_empty

  prepare_scenario codex-model
  codex_model_repo="$(new_repo codex-model)"
  run_aic "$codex_model_repo" --model codex-test-model
  grep -Fx -- '-m' "$AIC_TEST_AGENT_ARGS"
  grep -Fx -- 'codex-test-model' "$AIC_TEST_AGENT_ARGS"
  assert_tmp_empty

  prepare_scenario opencode-default
  opencode_default_repo="$(new_repo opencode-default)"
  run_aic "$opencode_default_repo" --agent opencode
  grep -Fx -- 'run' "$AIC_TEST_AGENT_ARGS"
  grep -Fx -- '--pure' "$AIC_TEST_AGENT_ARGS"
  grep -Fx -- '--format' "$AIC_TEST_AGENT_ARGS"
  grep -Fx -- 'json' "$AIC_TEST_AGENT_ARGS"
  grep -Fx -- '--agent' "$AIC_TEST_AGENT_ARGS"
  grep -Fx -- '-m' "$AIC_TEST_AGENT_ARGS"
  grep -Fx -- 'opencode/nemotron-3-ultra-free' "$AIC_TEST_AGENT_ARGS"
  opencode_agent="$(awk '
    previous == "--agent" { print; exit }
    { previous = $0 }
  ' "$AIC_TEST_AGENT_ARGS")"
  jq --exit-status --arg agent "$opencode_agent" '
    .agent[$agent].mode == "primary"
    and .agent[$agent].permission == "deny"
  ' "$AIC_TEST_AGENT_CONFIG" >/dev/null
  grep -F -- 'Create a Git commit message' "$AIC_TEST_AGENT_INPUT"
  grep -F -- 'change.txt' "$AIC_TEST_AGENT_INPUT"
  test "$(git -C "$opencode_default_repo" log -1 --pretty=%s)" = "Test commit"
  assert_opencode_session_deleted
  assert_tmp_empty

  prepare_scenario precedence
  precedence_repo="$(new_repo precedence)"
  (
    export AIC_AGENT=codex AIC_MODEL=environment-model
    run_aic "$precedence_repo" --agent opencode --model command-model
  )
  grep -Fx -- 'command-model' "$AIC_TEST_AGENT_ARGS"
  if grep -Fx -- 'environment-model' "$AIC_TEST_AGENT_ARGS"; then
    echo "AIC_MODEL unexpectedly overrode --model" >&2
    exit 1
  fi
  assert_opencode_session_deleted
  assert_tmp_empty

  prepare_scenario environment
  environment_repo="$(new_repo environment)"
  (
    export AIC_AGENT=opencode AIC_MODEL=environment-model
    run_aic "$environment_repo"
  )
  grep -Fx -- 'environment-model' "$AIC_TEST_AGENT_ARGS"
  assert_opencode_session_deleted
  assert_tmp_empty

  prepare_scenario invalid
  invalid_repo="$(new_repo invalid)"
  if run_aic "$invalid_repo" --agent invalid 2> "$test_root/invalid.err"; then
    echo "invalid agent unexpectedly succeeded" >&2
    exit 1
  fi
  grep -F -- 'unknown agent: invalid' "$test_root/invalid.err"
  git -C "$invalid_repo" diff --cached --quiet
  assert_tmp_empty

  prepare_scenario failure
  failure_repo="$(new_repo failure)"
  export AIC_TEST_AGENT_EXIT=23 AIC_TEST_AGENT_STDERR="provider unavailable"
  set +e
  run_aic "$failure_repo" --agent opencode 2> "$test_root/failure.err"
  failure_rc=$?
  set -e
  test "$failure_rc" -eq 23
  grep -F -- 'aic: opencode failed (exit 23)' "$test_root/failure.err"
  grep -F -- 'provider unavailable' "$test_root/failure.err"
  assert_opencode_session_deleted
  assert_tmp_empty

  prepare_scenario empty
  empty_repo="$(new_repo empty)"
  export AIC_TEST_AGENT_EMPTY=1
  if run_aic "$empty_repo" --agent opencode 2> "$test_root/empty.err"; then
    echo "empty OpenCode response unexpectedly succeeded" >&2
    exit 1
  fi
  grep -F -- 'aic: opencode generated an empty commit message' "$test_root/empty.err"
  assert_opencode_session_deleted
  assert_tmp_empty

  prepare_scenario session-delete-failure
  session_delete_failure_repo="$(new_repo session-delete-failure)"
  export AIC_TEST_SESSION_DELETE_EXIT=24
  if run_aic "$session_delete_failure_repo" --agent opencode \
    2> "$test_root/session-delete-failure.err"; then
    echo "failed OpenCode session cleanup unexpectedly succeeded" >&2
    exit 1
  fi
  grep -F -- 'aic: could not delete OpenCode session ses_aic_test' \
    "$test_root/session-delete-failure.err"
  grep -F -- 'session delete failed' "$test_root/session-delete-failure.err"
  if git -C "$session_delete_failure_repo" rev-parse --verify HEAD >/dev/null 2>&1; then
    echo "aic committed after failed OpenCode session cleanup" >&2
    exit 1
  fi
  assert_tmp_empty

  touch "$out"
''
